import { NextPage } from "next";
import Head from "next/head";

import Header from "../components/Header";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";
import { Speaker } from "../components/Speaker";

import morgsAvatar from "../public/morgs.png";

const speakers = [
  {
    firstName: "Chris",
    lastName: "Morgan",
    talk: "Building multiplayer apps with CRDTs; fast",
    role: "Tech Lead @ Dovetail",
    avatarUrl: morgsAvatar.src,
    description:
      "Currently slated for the 25th August, the mini-conf will start at 12 pm with first talks kicking off at 1 pm. We’ll then alternate between talks, break times, and a bit of fun - before breaking out for drinks and a discussion at the end of the event",
  },
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Delighters Conf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/ano2bsu.css" />
      </Head>

      <Header />
      {/*<Hero />*/}
      {speakers.map((speaker) => (
        <Speaker
          key={speaker.talk}
          firstName={speaker.firstName}
          lastName={speaker.lastName}
          imageSrc={speaker.avatarUrl}
          talkTitle={speaker.talk}
          speakerTitle={speaker.role}
          description={speaker.description}
        />
      ))}
    </div>
  );
};

export default Home;
